first commit of the year!

diff --git a/bin/pr b/bin/pr
--- a/bin/pr
+++ b/bin/pr
@@ -16,44 +16,61 @@ if [[ -f .env ]] ; then
 fi
 
 PR=$1
-URL="https://api.github.com/repos/msgphp/msgphp/pulls/$PR"
-if [[ ! -z "$GITHUB_TOKEN" ]] ; then
-    URL="$URL?access_token=$GITHUB_TOKEN"
+BRANCH="github-pr-${PR}"
+URL="https://api.github.com/repos/msgphp/msgphp/pulls/${PR}"
+if [[ ! -z $GITHUB_TOKEN ]] ; then
+    URL="$URL?access_token=${GITHUB_TOKEN}"
 fi
 
-BODY=$(curl -sS -w ">>>%{http_code}" $URL)
+if [[ ! $(git branch --list ${BRANCH}) ]] ; then
+    BODY=$(curl -sS -w ">>>%{http_code}" ${URL})
 
-if [[ ! $BODY =~ \>\>\>200\s*$ ]] ; then
-    echo -e "\e[34mError fetching pull request #$PR...\e[0m"
-    echo $BODY
-    exit 1
-fi
+    if [[ ! $BODY =~ \>\>\>200\s*$ ]] ; then
+        echo "Error fetching pull request #${PR}..."
+        echo ${BODY}
+        exit 1
+    fi
 
-BODY=$(echo $BODY | sed -e "s/>>>200$//" -e "s/\\\/\\\\\\\/g")
+    BODY=$(echo ${BODY} | sed -e "s/>>>200$//" -e "s/\\\/\\\\\\\/g")
 
-UPSTREAM_SSH_URL=$(php -r "echo (@json_decode(trim(<<<EOL
-$BODY
+    UPSTREAM_SSH_URL=$(cat <<EOF
+(@json_decode(trim(<<<EOL
+    ${BODY}
 EOL
-), true) ?: [])['head']['repo']['ssh_url'] ?? '';")
-UPSTREAM_BRANCH=$(php -r "echo (@json_decode(trim(<<<EOL
-$BODY
-EOL
-), true) ?: [])['head']['ref'] ?? '';")
+), true) ?: [])['head']['repo']['ssh_url'] ?? '';
+EOF
+    )
+    UPSTREAM_SSH_URL=$(php -r "echo ${UPSTREAM_SSH_URL}")
 
-if [[ -z "$UPSTREAM_SSH_URL" ]] ; then
-    echo "Upstream SSH URL not found for pull request \"$URL\""
-    exit 1
+    if [[ -z $UPSTREAM_SSH_URL ]] ; then
+        echo "Upstream SSH URL not found for pull request \"${URL}\""
+        exit 1
+    fi
+
+    UPSTREAM_BRANCH=$(cat <<EOF
+(@json_decode(trim(<<<EOL
+    ${BODY}
+EOL
+), true) ?: [])['head']['ref'] ?? '';
+EOF
+    )
+    UPSTREAM_BRANCH=$(php -r "echo ${UPSTREAM_BRANCH}")
+
+    echo "Adding pull request remote \"${UPSTREAM_SSH_URL}\"..."
+    git remote remove ${BRANCH} &> /dev/null
+    git remote add ${BRANCH} ${UPSTREAM_SSH_URL} --fetch --track ${UPSTREAM_BRANCH}
+    if [[ $? -eq 1 ]] ; then
+        git remote remove ${BRANCH}
+        echo "Pull request closed. Aborted."
+        exit 1
+    fi
+    git branch --set-upstream-to ${BRANCH}/${UPSTREAM_BRANCH}
 fi
 
 if [[ ! -z "$(git status --porcelain)" ]] ; then
-    echo "Current working must be clean to continue..."
+    echo "Current working directory must be clean to continue..."
     exit 1
 fi
 
-UPSTREAM_REMOTE="pr-$PR"
-
-git remote add $UPSTREAM_REMOTE $UPSTREAM_SSH_URL &> /dev/null
-git fetch $UPSTREAM_REMOTE
-git branch -Df $UPSTREAM_REMOTE &> /dev/null
-git checkout -b $UPSTREAM_REMOTE $UPSTREAM_REMOTE/$UPSTREAM_BRANCH
+git checkout ${BRANCH}
 git pull
